//HintName: TestNamespace.Examples.g.cs
// <auto-generated/>
using Godot;
namespace TestNamespace;
#nullable enable
partial class Examples
{
    private global::Godot.Node2D? _player;
    public partial global::Godot.Node2D Player()
    {
        return _player ??= GetNode<global::Godot.Node2D>("Player");
    }
    
    private global::Godot.Sprite2D? _sprite;
    public partial global::Godot.Sprite2D Sprite()
    {
        return _sprite ??= GetNode<global::Godot.Sprite2D>("Player/Sprite");
    }
}
#nullable restore