//HintName: TestNamespace.Examples.g.cs
// <auto-generated/>
using Godot;
namespace TestNamespace;
partial class Examples
{
    public partial global::Godot.Node2D OnReadyNode2DValid => GetNode<global::Godot.Node2D>("frezfrezf");
    
    public partial global::Godot.Node3D OnReadyNode3DValid()
    {
        return GetNode<global::Godot.Node3D>("/root/mynode");
    }
}
