//HintName: TestNamespace.Examples.g.cs
// <auto-generated/>
using Godot;
namespace TestNamespace;
#nullable enable
partial class Examples
{
    private global::Godot.Node2D? _onReadyNode2DValid;
    public partial global::Godot.Node2D OnReadyNode2DValid => _onReadyNode2DValid ??= GetNode<global::Godot.Node2D>("frezfrezf");
    
    private global::Godot.Node3D? _onReadyNode3DValid;
    public partial global::Godot.Node3D OnReadyNode3DValid()
    {
        return _onReadyNode3DValid ??= GetNode<global::Godot.Node3D>("/root/mynode");
    }
}
#nullable restore