//HintName: TestNamespace.Examples.g.cs
// <auto-generated/>
using Godot;
namespace TestNamespace;
partial class Examples
{
    public partial global::Godot.Node2D Player()
    {
        return GetNode<global::Godot.Node2D>("Player");
    }
}
