//HintName: TestNamespace.Examples.g.cs
// <auto-generated/>
using Godot;
namespace TestNamespace;
partial class Examples
{
    public partial global::Godot.Node2D Player => GetNode<global::Godot.Node2D>("Player");
    
    public partial global::Godot.Sprite2D Sprite => GetNode<global::Godot.Sprite2D>("Player/Sprite");
}
