//HintName: TestNamespace.Examples.g.cs
// <auto-generated/>
using Godot;
namespace TestNamespace;
partial class Examples
{
    public partial global::Godot.Node MyNode => GetNode<global::Godot.Node>("/root/mynode");
}
