name: Build & Test & Publish

on:
  push:
    #branches: [ "master" ]
  pull_request:
    #branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore
      working-directory: Shaka.Godot.OnReady
      run: dotnet restore
    - name: Build
      working-directory: Shaka.Godot.OnReady
      run: dotnet build --no-restore
      
    - name: Restore Tests
      working-directory: Shaka.Godot.OnReady.Tests
      run: dotnet restore
    - name: Build Tests
      working-directory: Shaka.Godot.OnReady.Tests
      run: dotnet build --no-restore
      
    - name: Test
      working-directory: Shaka.Godot.OnReady.Tests
      run: dotnet test --no-build --verbosity normal

    - name: Get Next Version
      uses: reecetech/version-increment@2024.10.1
      id: version
      with:
        scheme: semver
        increment: patch 
      
    - name: Tag
      run: git tag ${{ steps.version.outputs.v-version }}
    - name: Push Tag
      run: git push origin ${{ steps.version.outputs.v-version }}

    - name: Pack
      working-directory: Shaka.Godot.OnReady
      run: dotnet pack -c Release --no-build -p:PackageVersion=${{ steps.version.outputs.version }}
    - name: Nuget Publish
      working-directory: Shaka.Godot.OnReady
      run: dotnet nuget push Shaka.Godot.OnReady.${{ steps.version.outputs.version }}.nupkg --api-key ${{ secrets.API_KEY_NUGET_TEST }} --source https://int.nugettest.org/
